baseURL = "http://sale.polarfish.space/"
languageCode = "en-us"
title = "Распродажа в связи с переездом"
theme = "hugo-shopping-product-catalogue-simple"
[Params]
address = "Модиин, Адар 15"
phone = "054-717-21-88"
whatsappLink = "https://wa.me/972547172188"